Repository k8s-at-home/library-charts, pull requests merged in 2021-11, with the labels that each got.

#100 [common] add automountServiceAccountToken option
  charts/stable/common/Chart.yaml
  charts/stable/common/README.md
  charts/stable/common/templates/lib/controller/_pod.tpl
  charts/stable/common/values.yaml
Labels: enhancement, kind:incorrect-title, precommit:ok, lint:ok, unittest:ok, install:ok

#101 [common] add optional configmaps as part of library-charts
  charts/stable/common/README.md
  charts/stable/common/README_CHANGELOG.md.gotmpl
  charts/stable/common/templates/_all.tpl
  charts/stable/common/templates/_configmap.tpl
  charts/stable/common/templates/classes/_configmap.tpl
  charts/stable/common/tests/configmap_test.go
  charts/stable/common/values.yaml
Labels: enhancement, precommit:ok, lint:ok, unittest:ok, install:ok

#106 Update README.md
  README.md
Labels: kind:incorrect-title

#108 [common] Version 4.1.0
  charts/stable/common/Chart.yaml
  charts/stable/common/README.md
  charts/stable/common/README_CHANGELOG.md.gotmpl
  charts/stable/common/templates/_all.tpl
  charts/stable/common/templates/_configmap.tpl
  charts/stable/common/templates/addons/vpn/_networkpolicy.tpl
  charts/stable/common/templates/classes/_configmap.tpl
  charts/stable/common/templates/lib/controller/_pod.tpl
  charts/stable/common/templates/lib/controller/_volumes.tpl
  charts/stable/common/tests/configmap_test.go
  charts/stable/common/values.yaml
Labels: precommit:ok, lint:ok, unittest:ok, install:ok

#109 [common] add ipFamilyPolicy and ipFamilies
  charts/stable/common/Chart.yaml
  charts/stable/common/README.md
  charts/stable/common/README_CHANGELOG.md.gotmpl
  charts/stable/common/templates/classes/_service.tpl
  charts/stable/common/values.yaml
Labels: kind:incorrect-title, precommit:ok, lint:ok, unittest:ok, install:ok
